<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>7SBM-DayZ-Tools</ApplicationTitle>
    <AssemblyName>7SBM-DayZ-Tools</AssemblyName>
    <RootNamespace>DzAssets.Preview</RootNamespace>
    <Version>1.0.0</Version>
    <Company>7SBM</Company>
    <Product>7SBM-DayZ-Tools</Product>
    <ApplicationIcon>7SBM-DayZ-Tools.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DzAssets.Formats\DzAssets.Formats.csproj" />
  </ItemGroup>

</Project>
